settings:
  mode: retraining # training, retraining, inference
  task: follow_lane_carla # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: ppo_continuous # qlearn, dqn, ddpg, ppo
  simulator: carla # openai, carla, gazebo, sumo
  environment_set: carla_environments # gazebo_environments, carla_environments
  env: follow_lane # Town01, simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: auto_carla # f1, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: slow # slow, fast
  states: sp10 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  appended_states: 5
  stage: v
  rewards: followline_center # followline_center, followline_center_v_w_linear
  framework: baselines # TensorFlow, Pytorch
  total_episodes: 500000
  training_time: 72
  models_dir: "./checkpoints"
  recorder_carla_dir: "./recorders"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  steps_to_decrease: 3500
  entropy_factor: 0
  decrease_substraction: 0.005
  decrease_min: -5
  reward_params:
    function: pow
    punish_zig_zag_value: 2
    punish_ineffective_vel: 1 # velocity below which reward is not calculated (0)
    beta_1: 0

hot_reload_settings:
  visualize: True
  debug_waypoints: False

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  ppo:
    retrain_ppo_tf_model_name: /home/ruben/Desktop/2020-phd-ruben-lucas/src/RL-Studio/rl_studio/checkpoints/follow_lane_carla_ppo_continuous_auto_carla_baselines/20250620-194107/model_2420000_steps.zip
inference:
  ppo:
    inference_ppo_tf_actor_model_name:
    inference_ppo_tf_critic_model_name:

algorithm:
  ppo:
    gamma: 0.9
    epsilon: 0.1
    std_dev: 0.1
    episodes_update: 50 # dooing nothing here
    replay_memory_size: 50_000
    memory_fraction: 0.20
    critic_lr: 0.00003 # This is the only one applying to both now
    actor_lr: 0.0001
    model_name: PPO_Actor_conv2d32x64_Critic_conv2d32x64

agents:
  auto_carla:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [40] #TODO
  sp3:
    0: [10, 50, 150]
  sp5:
    0: [ 270, 275, 280, 380, 460 ]
#    projected: [50, 100, 150, 200, 250]
  sp10:
    0: [275, 280, 290, 295, 320, 360, 390, 420, 450, 480]
  spn:
    0: [10]

actions:
  slow:
    v: [-1, 1]
    w: [-0.5, 0.5]
   # b: [0, 1]

rewards:
  followline_center:
    from_10: 10
    from_02: 2
    from_01: 1
    penal: -100
    min_reward: 5_000
    highest_reward: 100
  followline_center_v_w_linear: # only for continuouscontinuous actions
    penal: 0
    min_reward: 1_000
    highest_reward: 100

carla_environments:
  follow_lane:
    env_name: CarlaEnv-v0
#    town: [Town01] #Town01, Town02, Town03, Town04, Town05, Town10HD
    town: [Town01, Town03, Town04] #Town01, Town02, Town03, Town04, Town05, Town10HD
    # Town01_Opt, Town02_Opt, Town03_Opt, Town04_Opt, Town05_Opt, Town10HD_Opt
    car: model1
    weather: ClearNoon #dynamic, argparse
    traffic_pedestrians: False
    city_lights: False
    car_lights: False
    estimated_steps: 500
    save_episodes: 5 # not used in this carla ppo
    save_every_step: 100 # not used in this carla ppo
    init_pose:
    goal_pose:
    filter: vehicle.*
    generation: "2"
    rolename: "hero" #name
    gamma: 2.2 #for camera
    sync: True #syncronous mode or async
    front_car: none # none, fixed, stopped, driving, incoming, outgoing
    detection_mode: carla_perfect_center
    fixed_delta_seconds: 0.1
    async_forced_delta_seconds: 0
    reset_threshold: 0.35
    alternate_pose: True
    spawn_points: #[
      #[278.050293, -368.798950, 0.807949, 0.095828, 16.101439, -2.257110],
      #[ -475.506342, 352.208710, 0.807793, 0.051254, 55.662395, 0.072115 ], #sliht curve to left
      #[12.93741, 157.040146, 0.09260, 0.051254, -90.375160, 0.1006703], # straight
      #[385.081470, -110.060329, 0.607339, 0.031453, 90.310402, 0.008101], # sharp to right
      #[199.221252, -367.893829, 0.809260, 0.248796, 0.152361, -0.002625], # straight
#      [ 334.204407,  13.815439, 0.608849, 1.506945, -179.198761, -1.299316] # long straight
      #   [235.603699, 12.395636, 5.228042, 3.577455, 0.124573, -0.008118], # straight reverse
   #   [389.385938, -179.152158, 0.457793, 0.082516, 270.889893, 0.078263] # straight reverse
    #]
    front_car_spawn_points: [
      [389.385938, -179.152158, 0.457793, 0.082516, 270.889893, 0.078263] # straight reverse
    ]
    waypoints_meters: 5 #distance between waypoints in meters
    waypoints_init: 6912 # {6912} 6927 1471
    waypoints_target: 959 #961
    waypoints_lane_id: -3
    waypoints_road_id: 1401

carla:
  carla_server: localhost
  carla_client: 5013
#  carla_client: [4013, 4015]
  manager_port: 8033
