Behaviors:
    Robot:
        Sensors:
            Cameras:
                Camera_0:
                    Name: 'camera_0'
                    Topic: '/carla/ego_vehicle/rgb_front/image'
                Camera_1:
                    Name: 'camera_1'
                    Topic: '/carla/ego_vehicle/rgb_view/image'
                Camera_2:
                    Name: 'camera_2'
                    Topic: '/carla/ego_vehicle/semantic_segmentation_front/image'
                Camera_3:
                    Name: 'camera_3'
                    Topic: '/carla/ego_vehicle/dvs_front/image'
            Pose3D:
                Pose3D_0:
                    Name: 'pose3d_0'
                    Topic: '/carla/ego_vehicle/odometry'
            BirdEyeView:
                BirdEyeView_0:
                    Name: 'bird_eye_view_0'
                    Topic: ''
            Speedometer:
                Speedometer_0:
                    Name: 'speedometer_0'
                    Topic: '/carla/ego_vehicle/speedometer'
        Actuators:
            CARLA_Motors:
                Motors_0:
                    Name: 'motors_0'
                    Topic: '/carla/ego_vehicle/vehicle_control_cmd'
                    MaxV: 3
                    MaxW: 0.3
                    
        BrainPath: [
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning.py',

            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning_tf_lite.py',
            ]
        PilotTimeCycle: 50
        AsyncMode: True
        Parameters:
            Model: [
                'pilotnet.h5',

                'optimized_pilotnet_models_tensorflow/pilotnet_model.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_dynamic_quant.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_int_quant.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_intflt_quant.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_float16_quant.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_quant_aware.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_pruned.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_pruned_quan.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_cqat_model.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_pqat_model.tflite',
                'optimized_pilotnet_models_tensorflow/pilotnet_pcqat_model.tflite'
                ]
            ImageCropped: True
            ImageSize: [ 100,50 ]
            ImageNormalized: True
            PredictionsNormalized: True
            GPU: True
            UseOptimized: True
            ImageTranform: ''
        Type: 'CARLA'
    Experiment:
        Name: "Experiment name"
        Description: "Experiment description"
        UseWorldTimeouts: True
        Timeout: [10] # for each world!
        Repetitions: 5
    Simulation:
        World: [
            configs/CARLA/CARLA_launch_files/town_02_anticlockwise_no_gui.launch,
            ]
        RandomSpawnPoint: False
        SpawnPoints: [
            [
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0",
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0",
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0",
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0",
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0"
            ]
        ]
    Dataset:
        In: '/tmp/my_bag.bag'
        Out: ''
    Stats:
        Out: './'
        PerfectLap: './perfect_bags/lap-simple-circuit.bag'
    Layout:
        Frame_0:
            Name: frame_0
            Geometry: [1, 1, 1, 1]
            Data: rgbimage
        Frame_1:
            Name: frame_1
            Geometry: [0, 1, 1, 1]
            Data: rgbimage
        Frame_2:
            Name: frame_2
            Geometry: [0, 2, 1, 1]
            Data: rgbimage
        Frame_3:
            Name: frame_3
            Geometry: [1, 2, 1, 1]
            Data: rgbimage
