settings:
  mode: retraining # training, retraining, inference
  task: follow_lane_carla # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: ddpg # qlearn, dqn, ddpg, ppo
  simulator: carla # openai, carla, gazebo, sumo
  environment_set: carla_environments # gazebo_environments, carla_environments
  env: follow_lane # Town01, simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: auto_carla # auto_carla, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: continuous # slow, fast
  states: sp5 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followlane_center # ffollowline_center, followline_center_v_w_linear
  framework: baselines # TensorFlow, Pytorch
  total_episodes: 5000000
  training_time: 72
  models_dir: "./checkpoints"
  recorder_carla_dir: "./recorders"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  debug_stats: false
  show_monitoring: false
  steps_to_decrease: 10000
  decrease_substraction: 0.003
  decrease_min: 0.003
  entropy_factor: 0
  use_curves_state: False
  reward_params:
    function: pow
    punish_zig_zag_value: 3
    punish_ineffective_vel: 1
    beta_1: 0

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  ddpg:
    retrain_ddpg_tf_model_name: /home/ruben/Desktop/2020-phd-ruben-lucas/RL_Unibotics/RL-Studio/rl_studio/checkpoints/follow_lane_carla_ddpg_auto_carla_baselines/20241113-100021/model_110000_steps.zip
inference:
  ddpg:
    retrain_ddpg_tf_model_name: /whatever

algorithm:
  ddpg:
    gamma: 0.92
    tau: 0.005
    std_dev: 0.5 # Note this std dev is applied to normalized actions (-1, 1) and generates noise between +-2*std_dev
    model_name: DDPG_Actor_conv2d32x64_Critic_conv2d32x64
    replay_memory_size: 10_000
    memory_fraction: 0.20
    critic_lr: 0.0002
    actor_lr: 0.0001
    buffer_capacity: 600180
    batch_size: 333

agents:
  auto_carla:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [40] #TODO
  sp3:
    0: [10, 50, 150]
  sp5:
    0: [280, 320, 360, 420, 460]
  sp10:
    0: [270, 280, 290, 300, 310, 330, 370, 400, 430, 460]
  spn:
    0: [10]

actions:
  continuous:
    v: [-1, 1]
    w: [-0.2, 0.2]
#    b: [0, 1]


rewards:
  followlane_center:

carla_environments:
  follow_lane:
    env_name: CarlaEnv-v0
    town: Town04 #Town01, Town02, Town03, Town04, Town05, Town10HD
    # Town01_Opt, Town02_Opt, Town03_Opt, Town04_Opt, Town05_Opt, Town10HD_Opt
    car: model1
    weather: ClearNoon #dynamic, argparse
    traffic_pedestrians: False
    city_lights: False
    car_lights: False
    estimated_steps: 3000
    save_episodes: 5 # not used in this carla ppo
    save_every_step: 100 # not used in this carla ppo
    goal_pose:
    init_pose:
    filter: vehicle.*
    generation: "2"
    rolename: "hero" #name
    gamma: 2.2 #for camera
    sync: True #syncronous mode or async
    detection_mode: carla_perfect  # carla_perfect
    fixed_delta_seconds: 0.05
    async_forced_delta_seconds: 0
    reset_threshold: 0.3
    alternate_pose: True
    spawn_points: [
      [ -475.506342, 352.208710, 0.807793, 0.051254, 55.662395, 0.072115 ],
      [12.493741, 157.040146, 0.809260, 0.051254, -90.375160, 0.1006703],
      [384.381470, -46.060329, 0.607339, 0.031453, 90.310402, 0.008101],
      [199.221252, -367.893829, 0.809260, 0.248796, 0.152361, -0.002625]
#      [235.603699, 12.395636, 5.128042, 3.577455, 0.124573, -0.008118],
#      [389.385938, -179.152158, 0.457793, 0.082516, 270.889893, 0.078263]
    ]
    waypoints_meters: 5 #distance between waypoints in meters
    waypoints_init: 6912 # {6912} 1471 6927 899 6294    waypoints_target: 959 #961
    waypoints_target: 959 #961
    waypoints_lane_id: -1
    waypoints_road_id: 8

carla:
  carla_server: localhost
  carla_client: 4002
  manager_port: 8022
