settings:
  mode: inference # training, retraining, inference
  task: follow_lane_carla # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: sac # qlearn, dqn, sac, ppo
  simulator: carla # openai, carla, gazebo, sumo
  environment_set: carla_environments # gazebo_environments, carla_environments
  env: follow_lane # Town01, simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: auto_carla # auto_carla, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: continuous # slow, fast
  states: sp10 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followlane_center # followline_center, followline_center_v_w_linear
  framework: TensorFlow # TensorFlow, Pytorch
  total_episodes: 500000
  training_time: 72
  models_dir: "./checkpoints"
  recorder_carla_dir: "./recorders"
  logs_dir: "./logs"
  metrics_dir: "./metrics"
  debug_stats: false
  show_monitoring: false
  steps_to_decrease: 15000
  decrease_substraction: 0.005
  decrease_min: 0.005
  inference_distance: 1400 # 200 [Town04] 2000 [Town05] 1400 [Town10HD]
  reward_params:
    function: pow
    punish_zig_zag_value: 1
    punish_ineffective_vel: 1
    beta_1: 0.9

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

inference:
  sac:
    inference_tf_model_name: /home/ruben/Desktop/2020-phd-ruben-lucas/src/RL-Studio/rl_studio/checkpoints/follow_lane_carla_sac_auto_carla_baselines/20250825-200403/model_1080000_steps_20250826-185544.zip

algorithm:
  sac:
    gamma: 0.9
    tau: 0.005
    std_dev: 0
    model_name: sac_Actor_conv2d32x64_Critic_conv2d32x64
    replay_memory_size: 10_000
    memory_fraction: 0.20
    critic_lr: 0.003
    actor_lr: 0.002
    buffer_capacity: 100_000
    batch_size: 120

agents:
  auto_carla:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [40] #TODO
  sp3:
    0: [10, 50, 150]
  sp5:
    0: [ 270, 280, 320, 400, 460 ]
    1: speed/40
    2: w_angle
    3: calculate_curvature_from
    4: previous_action[0]
    5: previous_action[1]
  sp10:
    0: [275, 280, 290, 295, 320, 360, 390, 420, 450, 480]
#    0: [270, 280, 290, 300, 310, 330, 370, 400, 430, 460]
  spn:
    0: [10]

actions:
  continuous:
    v: [-1, 1]
    w: [-0.5, 0.5]


rewards:
  followlane_center:

carla_environments:
  follow_lane:
    env_name: CarlaEnv-v0
    town: Town02 #Town01, Town02, Town03, Town04, Town05, Town10HD
    # Town01_Opt, Town02_Opt, Town03_Opt, Town04_Opt, Town05_Opt, Town10HD_Opt
    car: model1
    weather: ClearNoon #dynamic, argparse
    traffic_pedestrians: False
    city_lights: False
    car_lights: False
    estimated_steps: 5000
    save_episodes: 5 # not used in this carla ppo
    save_every_step: 100 # not used in this carla ppo
    init_pose:
    goal_pose:
    filter: vehicle.*
    generation: "2"
    rolename: "hero" #name
    gamma: 2.2 #for camera
    sync: false #syncronous mode or async
    detection_mode: carla_perfect # OJO!! De la misma manera que otros parametros. Esto no hace nada en BM
    fixed_delta_seconds: 0.1
    async_forced_delta_seconds: 0
    reset_threshold: 0.3
    alternate_pose: false
    waypoints_meters: 5 #distance between waypoints in meters
    waypoints_init: 21 # 6927  1471 899
    waypoints_target: 959 #961
    waypoints_lane_id: -1
    waypoints_road_id: 8

carla:
  carla_server: localhost
  carla_client: 2000
  manager_port: 8011
