import re

old_text = """
\section{Related Work}
As autonomous driving evolves, Reinforcement Learning (RL) has been applied to a wide variety of driving tasks, as comprehensively reviewed in recent surveys by Zhao et al.~\cite{zhao2024survey} and Wu et al.~\cite{wu2024survey} on Deep Reinforcement Learning (DRL) applications and behavior planning, respectively. These surveys highlight the rapid adoption of RL-based methods across autonomous driving decision-making problems, while also identifying persistent challenges related to training stability, generalization, and evaluation consistency.
A significant portion of the literature focuses on foundational driving tasks such as lane following, which provides a controlled yet meaningful setting for studying continuous control. Prior work has explored different DRL algorithms in this context, including improved stability for DDPG-based controllers~\cite{hua2022exploration}, comparisons between value-based and policy-gradient methods~\cite{sabbir2025comparative}, and entropy-regularized approaches for high-speed lane tracking~\cite{liu2024highspeed}. While these studies demonstrate the feasibility of DRL for lane-following control, they typically evaluate a limited number of algorithms, rely on narrow scenario distributions, or lack rigorous control of training stochasticity, making it difficult to draw principled conclusions about algorithm selection and robustness.
Beyond lane following, RL and DRL have been applied to increasingly complex autonomous driving tasks, including intersection navigation~\cite{benelallid2023intersection,shankar2025deep, liu2021rlbenchmark, jayawardana2023,cederle2024distributed,Spatharis02012024}, lane changing~\cite{wang2024benchmarking}, car following~\cite{liu2024comparative,chen2023follownet,Marin04122025}, driving under diverse weather conditions~\cite{tang2020,almalioglu2022,lee2024robust,BenElallid02112025}, ramp merging~\cite{chen2023rampmerging}, and overtaking~\cite{cui2023multiinput, li2020deepRL}. Although these studies confirm the versatility of RL-based approaches, their diversity in tasks, environments, and evaluation protocols further reinforces the need for standardized, task-focused benchmarks that isolate core decision-making and control capabilities.
Vision-based perception, particularly using a single front-facing camera, is a common and cost-effective setup in autonomous driving research. Recent work on camera-only Bird’s-Eye-View perception~\cite{geiger2012kitti,busch2023improved,unger2023multicamera} and lightweight detection architectures~\cite{wu2022yolop,howard2017mobilenets,liu2016ssd} demonstrates that vision-only systems can achieve competitive performance while remaining scalable. However, most perception-focused studies emphasize representation learning rather than downstream control stability, and they are often evaluated independently of systematic decision-making benchmarks. In this work, perception is therefore treated as a fixed input modality, allowing the analysis to focus exclusively on control and decision-making behavior.
Autonomous driving decision-making has historically relied on a broad range of paradigms, including rule-based systems~\cite{bouchard2015rulebased}, finite state machines~\cite{bae2020fsm}, machine learning, imitation learning~\cite{codevilla2018il,cheng2023pluto,moncalvillo2024ackermann}, and reinforcement learning. Rule-based and finite state machine approaches offer interpretability and verifiability but scale poorly as environmental complexity increases. Machine learning and imitation learning methods enable data-driven control and can achieve strong performance in nominal conditions, yet they often struggle with generalization beyond the distribution of expert demonstrations or training data. These limitations motivate the use of reinforcement learning, which explicitly optimizes long-term behavior under uncertainty and interaction.
Reinforcement Learning has become a central paradigm for continuous decision-making in autonomous driving, with several benchmark environments proposed to evaluate agent performance~\cite{liu2021rlbenchmark,lavington2024torchdriveenv}. However, classical RL methods face challenges related to sample efficiency and training instability, particularly in high-dimensional, continuous-action settings. Deep Reinforcement Learning addresses these challenges by leveraging deep neural networks to approximate policies and value functions, enabling effective learning from rich sensory inputs. As documented in recent surveys~\cite{kiran2021rl,prasuna2024deep,singh2025improvised}, DRL now underpins many end-to-end and modular autonomous driving systems.
In complex continuous-control problems, DRL is often integrated within hierarchical or decoupled architectures, where high-level planners generate reference trajectories or target velocities and low-level DRL agents execute smooth control commands~\cite{wang2024benchmarking,qiao2020hierarchical}. This design aligns with established practices for improving stability and interpretability. Nevertheless, performance in such systems remains highly sensitive to algorithm choice, training methodology, and scenario diversity.
Despite the widespread use of DRL, systematic comparisons between dominant DRL algorithms—such as Proximal Policy Optimization (PPO)~\cite{schulman2017proximal}, Deep Deterministic Policy Gradient (DDPG)~\cite{lillicrap2015continuous}, Twin Delayed DDPG (TD3)~\cite{fujimoto2018addressing}, and Soft Actor-Critic (SAC)~\cite{haarnoja2019sac}—remain limited. Existing studies often evaluate these methods under restricted conditions, with few repetitions, limited control of randomness, or narrow environment diversity~\cite{evans2024racing,li2025sharpturns}. As a result, reported performance differences may reflect experimental artifacts rather than intrinsic algorithmic properties. Recent analyses suggest that stability-enhanced and entropy-regularized actor-critic methods often outperform earlier approaches~\cite{liu2024evaluation,xu2024lanechanging,park2025comparative}, but these findings require validation under controlled and reproducible benchmarks.
To address these limitations, this work conducts a rigorous comparative evaluation of PPO, DDPG, TD3, and SAC in a focused lane-following task. By isolating the decision-making layer in a high-fidelity simulation environment, controlling for training stochasticity, and systematically varying scenario diversity, we provide an evidence-based assessment of algorithm performance, stability, and generalization. Furthermore, an ablation study explicitly analyzes how different sources of training variety contribute to safety and robustness. This positioning differentiates the present study from prior work and directly addresses the need for principled algorithm selection in autonomous driving control.
"""

def get_refs(text):
    cites = re.findall(r'\\cite\{([^}]+)\}', text)
    refs = []
    for c in cites:
        refs.extend([r.strip() for r in c.split(',')])
    return set(refs)

old_refs = get_refs(old_text)
print(f"Old refs count: {len(old_refs)}")
print(sorted(old_refs))
