new_rw = r"""\section{Related Work}

Autonomous driving decision-making has historically relied on a broad range of paradigms. Among early approaches, Bouchard et al.~\cite{bouchard2015rulebased} proposed a rule-based behavior planner grounded in formal logic for structured environments, while Bae et al.~\cite{bae2020fsm} implemented a finite state machine-based behavioral planner to explicitly manage urban driving states such as cruising and stopping. These offer high interpretability but often scale poorly as environmental complexity increases due to the impossibility of anticipating every driving scenario. To overcome these limitations, machine learning approaches, particularly imitation learning, have been widely adopted to learn end-to-end control from expert demonstrations. For instance, Codevilla et al.~\cite{codevilla2018il} introduced conditional imitation learning to enable models to follow high-level navigational commands; Cheng et al.~\cite{cheng2023pluto} presented PLUTO, an imitation learning-based planning framework designed to improve high-fidelity trajectory prediction and decision-making performance; and Moncalvillo et al.~\cite{moncalvillo2024ackermann} adapted imitation learning techniques to account for the physical constraints imposed by Ackermann steering geometry. While these models achieve strong performance under nominal conditions, they frequently struggle with generalization when encountering out-of-distribution events or safety-critical edge cases not present in the training dataset.

To address the challenges of generalization and long-term planning under uncertainty, reinforcement learning, and specifically deep reinforcement learning, has emerged as a central paradigm. By leveraging deep neural networks to approximate policies and value functions, deep reinforcement learning enables effective learning from rich sensory inputs and explicit optimization of long-term behavior. Recent surveys document this evolution: Zhao et al.~\cite{zhao2024survey} categorized deep reinforcement learning applications in autonomous driving and discussed persistent safety challenges, while Wu et al.~\cite{wu2024survey} focused specifically on behavior planning in complex traffic interactions. Concurrently, several benchmark environments have been proposed to standardize agent evaluation; Lavington et al.~\cite{lavington2024torchdriveenv} introduced TorchDriveEnv to facilitate training against reactive non-playable characters, and Liu et al.~\cite{liu2021rlbenchmark} developed a benchmark specifically targeting intersection scenarios. Comprehensive reviews further contextualize these developments: Kiran et al.~\cite{kiran2021rl} examined state-space representation and reward shaping strategies, Prasuna and Potturu~\cite{prasuna2024deep} discussed sample efficiency and the sim-to-real gap, and Singh et al.~\cite{singh2025improvised} explored approaches for safer deployment in real-time environments. As a result, deep reinforcement learning now underpins many end-to-end and modular autonomous driving systems.

Beyond foundational control, deep reinforcement learning has been applied to a wide array of increasingly complex autonomous driving tasks. For intersection navigation, Ben Elallid et al.~\cite{benelallid2023intersection} demonstrated a DRL-based approach aimed at reducing delays in unsignalized intersections, Shankar et al.~\cite{shankar2025deep} evaluated reinforcement learning agents in uncontrolled intersection scenarios representative of Indian road conditions, and Spatharis and Blekas~\cite{Spatharis02012024} applied multi-agent reinforcement learning to improve coordination and traffic efficiency through decentralized decision-making. Furthermore, Jayawardana et al.~\cite{jayawardana2023} emphasized eco-driving strategies in multi-agent contexts using the INTERSECTIONZOO benchmark, and Cederle et al.~\cite{cederle2024distributed} proposed a distributed coordination approach to reduce reliance on centralized intersection infrastructure. In the context of lane changing, Wang et al.~\cite{wang2024benchmarking} established a benchmark evaluating how different algorithms balance safety and traffic flow efficiency during merging maneuvers. Similarly, for car-following and freeway decision-making, Liu et al.~\cite{liu2024comparative} focused on high-speed stability, Chen et al.~\cite{chen2023follownet} introduced the FollowNet dataset and benchmark for modeling and evaluating car-following behavior and safe headway control, and Marin et al.~\cite{Marin04122025} developed a deep reinforcement learning framework for safe and efficient autonomous car-following, balancing collision avoidance and traffic flow performance. Robustness to environmental factors has also been explored: Tang et al.~\cite{tang2020} empirically established baselines for LiDAR degradation in rain and fog, Almalioglu et al.~\cite{almalioglu2022} presented a positioning system fusing sensory inputs across varying weather conditions, Lee et al.~\cite{lee2024robust} proposed a hybrid deep learning control architecture robust to degraded visual inputs, and Ben Elallid et al.~\cite{BenElallid02112025} evaluated reinforcement learning-based control policies under diverse lighting and weather conditions to assess robustness and generalization. Other complex maneuvers have similarly benefited from dynamic trajectory optimization; Chen et al.~\cite{chen2023rampmerging} applied multi-agent reinforcement learning to highway on-ramp merging, Cui et al.~\cite{cui2023multiinput} utilized a specialized experience replay mechanism to learn from diverse sensory inputs during overtaking, and Li et al.~\cite{li2020deepRL} proposed a deep reinforcement learning approach for autonomous overtaking, emphasizing safe timing and passing strategies in continuous traffic.

In complex continuous-control problems, reinforcement learning is frequently integrated into hierarchical or decoupled architectures. For example, Qiao et al.~\cite{qiao2020hierarchical} proposed a hierarchical architecture in which a high-level planner selects maneuvers and a low-level controller executes them, improving modularity and interpretability. From a perception standpoint, vision-based setups remain common and cost-effective. Geiger et al.~\cite{geiger2012kitti} established the KITTI benchmark, which laid foundational groundwork for stereo vision and 3D object detection in autonomous driving research. More recently, Busch et al.~\cite{busch2023improved} enhanced single-camera Bird's-Eye-View perception by leveraging multi-camera data during training, and Unger et al.~\cite{unger2023multicamera} developed a framework providing a holistic 360-degree environmental representation to support decision-making. Lightweight detection architectures also play a crucial role; Wu et al.~\cite{wu2022yolop} introduced the YOLOP network for simultaneous traffic object detection and drivable area segmentation, Howard et al.~\cite{howard2017mobilenets} tailored MobileNet convolutional architectures for embedded vision, and Liu et al.~\cite{liu2016ssd} offered fast 2D object detection suitable for real-time driving via the Single Shot MultiBox Detector.

A significant portion of the foundational literature focuses on the specific task of lane following, which serves as a critical testbed for continuous control. Studies in this area have targeted different aspects of control optimization: Hua et al.~\cite{hua2022exploration} refined the exploration strategy of Deep Deterministic Policy Gradient to improve lateral control stability, Liu et al.~\cite{liu2024highspeed} proposed an entropy-regularized controller maintaining precision at high speeds, and Sabbir~\cite{sabbir2025comparative} compared Proximal Policy Optimization and Double Deep Q-Networks, reporting stronger performance of PPO in continuous control settings. Despite widespread adoption, systematic comparisons among dominant deep reinforcement learning algorithms—such as Proximal Policy Optimization, originally introduced by Schulman et al.~\cite{schulman2017proximal} using a clipped surrogate objective; Deep Deterministic Policy Gradient, adapted for continuous action spaces by Lillicrap et al.~\cite{lillicrap2015continuous}; Twin Delayed Deep Deterministic Policy Gradient, proposed by Fujimoto et al.~\cite{fujimoto2018addressing}, which was designed to mitigate overestimation bias in actor-critic methods; and Soft Actor-Critic, introduced by Haarnoja et al.~\cite{haarnoja2019sac}, which is an entropy-regularized algorithm designed to balance exploration and exploitation—remain relatively limited in autonomous driving contexts and often yield varying results. While some studies evaluate these methods under restricted conditions—such as Evans et al.~\cite{evans2024racing}, who compared deep reinforcement learning architectures in the context of autonomous racing with lap time as a primary metric, or Li et al.~\cite{li2025sharpturns}, who analyzed failure modes on consecutive sharp turns—broader analyses increasingly suggest that stability-enhanced actor-critic methods exhibit improved robustness. Specifically, Liu~\cite{liu2024evaluation} conducted a systematic evaluation of actor-critic algorithms across standard continuous control benchmarks, Xue et al.~\cite{xu2024lanechanging} compared reinforcement learning methods for cooperative lane-changing, and Park et al.~\cite{park2025comparative} evaluated algorithms under urban driving challenges and regulatory constraints within the CARLA simulator."""

with open("JITS/JITS_2_0220.tex", "r") as f:
    content = f.read()

start = content.find(r"\section{Related Work}")
end = content.find(r"\section{Materials and Methods}")

old_rw = content[start:end]

with open("JITS/JITS_2_0220.tex", "w") as f:
    f.write(content.replace(old_rw, new_rw + "\n"))
    
