import re

text = """
Autonomous driving decision-making has historically relied on a broad range of paradigms. Among early approaches, Bouchard et al.~\cite{bouchard2015rulebased} proposed a rule-based behavior planner that uses formal logic for structured environments, while Bae et al.~\cite{bae2020fsm} implemented a finite state machine to explicitly manage urban driving states like cruising and stopping. These offer high interpretability but often scale poorly as environmental complexity increases due to the impossibility of anticipating every driving scenario. To overcome these limitations, machine learning approaches, particularly imitation learning, have been widely adopted to learn end-to-end control from expert demonstrations. For instance, Codevilla et al.~\cite{codevilla2018il} introduced conditional imitation learning to allow models to follow high-level navigational commands; Cheng et al.~\cite{cheng2023pluto} presented the PLUTO framework to push performance limits via high-fidelity trajectory planning; and Moncalvillo et al.~\cite{moncalvillo2024ackermann} adapted imitation learning specifically to the physical constraints of Ackermann steering geometry. While these models achieve strong performance under nominal conditions, they frequently struggle with generalization when encountering out-of-distribution events or safety-critical edge cases not present in the training dataset.

To address the challenges of generalization and long-term planning under uncertainty, reinforcement learning, and specifically deep reinforcement learning, has emerged as a central paradigm. By leveraging deep neural networks to approximate policies and value functions, deep reinforcement learning enables effective learning from rich sensory inputs and explicit optimization of long-term behavior. Recent literature provides extensive tracking of this shift: Zhao et al.~\cite{zhao2024survey} categorized deep reinforcement learning applications and detailed ongoing safety challenges, while Wu et al.~\cite{wu2024survey} focused specifically on behavior planning in complex traffic interactions. Concurrently, several benchmark environments have been proposed to standardize agent evaluation; Lavington et al.~\cite{lavington2024torchdriveenv} introduced TorchDriveEnv to emphasize training against reactive non-playable characters, and Liu et al.~\cite{liu2021rlbenchmark} created a benchmark dedicated specifically to intersection scenarios. As documented in other comprehensive reviews—where Kiran et al.~\cite{kiran2021rl} covered state-space representation and reward shaping, Prasuna and Potturu~\cite{prasuna2024deep} highlighted sample efficiency and the sim-to-real gap, and Singh et al.~\cite{singh2025improvised} explored techniques for safer integration in real-time environments—deep reinforcement learning now underpins many end-to-end and modular autonomous driving systems.

Beyond foundational control, deep reinforcement learning has been applied to a wide array of increasingly complex autonomous driving tasks. For intersection navigation, Ben Elallid et al.~\cite{benelallid2023intersection} demonstrated an approach minimizing delays in unsignalized intersections, Shankar et al.~\cite{shankar2025deep} evaluated agents navigating the chaotic dynamics of uncontrolled Indian roads, and Spatharis and Blekas~\cite{Spatharis02012024} optimized global traffic flow through local decisions using multi-agent reinforcement learning. Furthermore, Jayawardana et al.~\cite{jayawardana2023} prioritized eco-driving in multi-agent contexts with the INTERSECTIONZOO benchmark, and Cederle et al.~\cite{cederle2024distributed} proposed a distributed approach to reduce reliance on centralized intersection infrastructure. In the context of lane changing, Wang et al.~\cite{wang2024benchmarking} established a benchmark comparing how different algorithms balance safety and traffic flow during merging maneuvers. Similarly, for car-following and freeway decision-making, Liu et al.~\cite{liu2024comparative} focused on high-speed stability, Chen et al.~\cite{chen2023follownet} introduced the FollowNet benchmark to evaluate safe headways, and Marin et al.~\cite{Marin04122025} developed a framework optimizing behavior for both collision avoidance and fuel efficiency. Robustness to environmental factors has also been explored: Tang et al.~\cite{tang2020} empirically established baselines for LiDAR degradation in rain and fog, Almalioglu et al.~\cite{almalioglu2022} presented a positioning system fusing sensory inputs across all weather conditions, Lee et al.~\cite{lee2024robust} investigated hybrid-learning networks for degraded visual inputs, and Ben Elallid et al.~\cite{BenElallid02112025} evaluated control policies ensuring consistency across diverse lighting and weather scenarios. Other complex maneuvers have similarly benefited from dynamic trajectory optimization; Chen et al.~\cite{chen2023rampmerging} applied multi-agent reinforcement learning to highway on-ramp merging, Cui et al.~\cite{cui2023multiinput} utilized a specialized experience replay buffer for learning from diverse sensory data during overtaking, and Li et al.~\cite{li2020deepRL} focused on timing and safe passing in continuous traffic.

In complex continuous-control problems, reinforcement learning is frequently integrated into hierarchical or decoupled architectures. For example, Qiao et al.~\cite{qiao2020hierarchical} proposed a hierarchical structure where a high-level planner selects maneuvers and a low-level agent executes commands, aligning with established practices for improving system interpretability. From a perception standpoint, vision-based setups remain common and cost-effective. Geiger et al.~\cite{geiger2012kitti} laid the groundwork with the KITTI benchmark for stereo and 3D object detection. More recently, Busch et al.~\cite{busch2023improved} enhanced single-camera Bird's-Eye-View perception utilizing multi-camera data during training, and Unger et al.~\cite{unger2023multicamera} created a framework for a holistic 360-degree view to aid decision-making. Lightweight detection architectures also play a crucial role; Wu et al.~\cite{wu2022yolop} introduced the YOLOP network for simultaneous traffic object detection and drivable area segmentation, Howard et al.~\cite{howard2017mobilenets} tailored MobileNet convolutional architectures for embedded vision, and Liu et al.~\cite{liu2016ssd} offered fast 2D object detection suitable for real-time driving via the Single Shot MultiBox Detector.

A significant portion of the foundational literature focuses on the specific task of lane following, which serves as a critical testbed for continuous control. Studies in this area have aimed to optimize different facets of control: Hua et al.~\cite{hua2022exploration} improved the exploration strategy for the Deep Deterministic Policy Gradient algorithm to enhance lateral control stability, Liu et al.~\cite{liu2024highspeed} proposed an entropy-regularized controller maintaining precision at high speeds, and Sabbir~\cite{sabbir2025comparative} contrasted Proximal Policy Optimization and Double Deep Q-Networks, noting the former's superiority in continuous control. Despite widespread use, broad systematic comparisons between dominant deep reinforcement learning algorithms—such as Proximal Policy Optimization, originally formulated by Schulman et al.~\cite{schulman2017proximal} using a clipped surrogate objective; Deep Deterministic Policy Gradient, adapted for continuous action spaces by Lillicrap et al.~\cite{lillicrap2015continuous}; Twin Delayed Deep Deterministic Policy Gradient, which Fujimoto et al.~\cite{fujimoto2018addressing} designed to address overestimation bias; and Soft Actor-Critic, an entropy-regularized algorithm balancing exploration and exploitation by Haarnoja et al.~\cite{haarnoja2019sac}—often yield varying results. While some studies evaluate these methods under restricted conditions—such as Evans et al.~\cite{evans2024racing} focusing on lap time in autonomous racing, or Li et al.~\cite{li2025sharpturns} highlighting failure modes on consecutive sharp turns—recent broader analyses increasingly suggest that stability-enhanced actor-critic methods offer superior resilience. Specifically, Liu~\cite{liu2024evaluation} provided a systematic evaluation of actor-critic methods across standard continuous control benchmarks, Xue et al.~\cite{xu2024lanechanging} compared algorithms specifically for cooperative lane-changing, and Park et al.~\cite{park2025comparative} evaluated algorithms against urban driving challenges and regulatory constraints within the CARLA simulator.
"""

# split text into sentences roughly by finding punctuation followed by space or end of string, while keeping the punctuation.
# but we have semi-colons joining descriptions! So let's split by clauses separated by commas, semi-colons, or periods where the cite block resides.
# Actually, just regex matching the immediate context surrounding \cite{} is safer.
# For simplicity, we can split by ; and .

sentences = re.split(r'(?<=[\.\;])\s+', text.strip().replace('\n', ' '))

ref_to_sentence = {}
for sentence in sentences:
    matches = re.findall(r'\\cite\{([^}]+)\}', sentence)
    if matches:
        keys = []
        for m in matches:
            keys.extend([k.strip() for k in m.split(',')])
        for k in keys:
            if k not in ref_to_sentence:
                ref_to_sentence[k] = []
            ref_to_sentence[k].append(sentence)

output = "# Exact Text Used in the Article for Each Reference\n\nThis document shows the exact clause or sentence in the newly rewritten 'Related Work' section corresponding to each of the 47 references.\n\n"

for key in sorted(ref_to_sentence.keys()):
    output += f"### {key}\n"
    for s in ref_to_sentence[key]:
        output += f"> {s}\n\n"

with open('/home/ruben/Desktop/2020-phd-ruben-lucas/docs/assets/articles/2026_article_attempt/references_analysis.md', 'w') as f:
    f.write(output)
